// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvwS9t6Vsx1k9aIOTmsVGU3f7SLf57QH8',
    appId: '1:249838020251:web:2be35db22213396533083e',
    messagingSenderId: '249838020251',
    projectId: 'onwork-6e96d',
    authDomain: 'onwork-6e96d.firebaseapp.com',
    storageBucket: 'onwork-6e96d.firebasestorage.app',
    measurementId: 'G-F522HM208R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBtK4N7pMWJpBpwUYWrf8x5YlUJ1hyT3I',
    appId: '1:249838020251:android:53bdc3c0a370c6a533083e',
    messagingSenderId: '249838020251',
    projectId: 'onwork-6e96d',
    storageBucket: 'onwork-6e96d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRGUTugn_5-qn1GKpI6k-OSYd3ebJXmWM',
    appId: '1:249838020251:ios:5926a58bff5cc04a33083e',
    messagingSenderId: '249838020251',
    projectId: 'onwork-6e96d',
    storageBucket: 'onwork-6e96d.firebasestorage.app',
    iosBundleId: 'com.example.serviceprovider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRGUTugn_5-qn1GKpI6k-OSYd3ebJXmWM',
    appId: '1:249838020251:ios:5926a58bff5cc04a33083e',
    messagingSenderId: '249838020251',
    projectId: 'onwork-6e96d',
    storageBucket: 'onwork-6e96d.firebasestorage.app',
    iosBundleId: 'com.example.serviceprovider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvwS9t6Vsx1k9aIOTmsVGU3f7SLf57QH8',
    appId: '1:249838020251:web:de22458ea4e7bf5633083e',
    messagingSenderId: '249838020251',
    projectId: 'onwork-6e96d',
    authDomain: 'onwork-6e96d.firebaseapp.com',
    storageBucket: 'onwork-6e96d.firebasestorage.app',
    measurementId: 'G-D3Z6RXYWMS',
  );
}
